-- Azzaro products INSERT
-- price = precio base, priceTransfer = precio * 0.80 (efectivo/transferencia con 20% OFF)

INSERT INTO "Product" (id, name, slug, description, brand, category, gender, occasion, notes, images, price, "priceTransfer", stock, "isActive", "isFeatured", "freeShipping", "createdAt", "updatedAt")
VALUES
(
  gen_random_uuid()::text,
  'Azzaro The Most Wanted Eau de Toilette 100ml',
  'azzaro-the-most-wanted-eau-de-toilette-100ml',
  'Azzaro The Most Wanted Eau de Toilette 100ml. Una fragancia audaz y seductora para el hombre moderno.',
  'Azzaro',
  'DESIGNER',
  'MASCULINO',
  ARRAY[]::text[],
  '{"top": [], "heart": [], "base": []}',
  ARRAY['/PERFUMES%20SAID/AZZARO/Azzaro%20The%20Most%20Wanted%20Eau%20de%20Toilette%20100ml%20.JPG'],
  130000,
  104000,
  10,
  true,
  false,
  false,
  NOW(),
  NOW()
),
(
  gen_random_uuid()::text,
  'Azzaro The Most Wanted Intense 100ml',
  'azzaro-the-most-wanted-intense-100ml',
  'Azzaro The Most Wanted Intense 100ml. Versión intensa y envolvente de la icónica fragancia.',
  'Azzaro',
  'DESIGNER',
  'MASCULINO',
  ARRAY[]::text[],
  '{"top": [], "heart": [], "base": []}',
  ARRAY['/PERFUMES%20SAID/AZZARO/Azzaro%20The%20Most%20Wanted%20Intense%20100ml%20.JPG'],
  170000,
  136000,
  10,
  true,
  false,
  false,
  NOW(),
  NOW()
),
(
  gen_random_uuid()::text,
  'Azzaro Wanted Forever Elixir 100ml',
  'azzaro-wanted-forever-elixir-100ml',
  'Azzaro Wanted Forever Elixir 100ml. Un elixir de larga duración, opulento y magnético.',
  'Azzaro',
  'DESIGNER',
  'MASCULINO',
  ARRAY[]::text[],
  '{"top": [], "heart": [], "base": []}',
  ARRAY['/PERFUMES%20SAID/AZZARO/Azzaro%20Wanted%20Forever%20Elixir%20100ml.JPG'],
  185000,
  148000,
  10,
  true,
  false,
  false,
  NOW(),
  NOW()
),
(
  gen_random_uuid()::text,
  'Azzaro The Most Wanted Eau de Parfum 100ml',
  'azzaro-the-most-wanted-eau-de-parfum-100ml',
  'Azzaro The Most Wanted Eau de Parfum 100ml. La elegancia y el poder de la fragancia más deseada.',
  'Azzaro',
  'DESIGNER',
  'MASCULINO',
  ARRAY[]::text[],
  '{"top": [], "heart": [], "base": []}',
  ARRAY['/PERFUMES%20SAID/AZZARO/Azzaro%20The%20Most%20Wanted%20Eau%20de%20Parfum%20100ml.JPG'],
  145000,
  116000,
  10,
  true,
  false,
  false,
  NOW(),
  NOW()
),
(
  gen_random_uuid()::text,
  'Azzaro Wanted Eau de Toilette 100ml',
  'azzaro-wanted-eau-de-toilette-100ml',
  'Azzaro Wanted Eau de Toilette 100ml. Fresco, magnético y decidido.',
  'Azzaro',
  'DESIGNER',
  'MASCULINO',
  ARRAY[]::text[],
  '{"top": [], "heart": [], "base": []}',
  ARRAY['/PERFUMES%20SAID/AZZARO/Azzaro%20Wanted%20Eau%20de%20Toilette%20100ml%20.JPG'],
  110000,
  88000,
  10,
  true,
  false,
  false,
  NOW(),
  NOW()
),
(
  gen_random_uuid()::text,
  'Azzaro Wanted Eau de Parfum 50ml',
  'azzaro-wanted-eau-de-parfum-50ml',
  'Azzaro Wanted Eau de Parfum 50ml. Intensidad y carisma en un frasco compacto.',
  'Azzaro',
  'DESIGNER',
  'MASCULINO',
  ARRAY[]::text[],
  '{"top": [], "heart": [], "base": []}',
  ARRAY['/PERFUMES%20SAID/AZZARO/Azzaro%20Wanted%20Eau%20de%20Parfum%2050ml%20.JPG'],
  110000,
  88000,
  10,
  true,
  false,
  false,
  NOW(),
  NOW()
);
