    -- SQL generado automaticamente para actualizar imagenes de productos
    -- Tabla Prisma: "Product" | columnas: brand, name, images (array)
    -- Pega esto en Supabase -> SQL Editor y ejecuta

    -- ======= AFNAN =======
    UPDATE "Product" SET images = ARRAY['/PERFUMES%20SAID/AFNAN/9AM%20DIVE.jpg'] WHERE brand = 'AFNAN' AND name ILIKE '%9AM%' AND name ILIKE '%DIVE%';
    UPDATE "Product" SET images = ARRAY['/PERFUMES%20SAID/AFNAN/9PM%20PUOR%20FEMME.jpg'] WHERE brand = 'AFNAN' AND name ILIKE '%9PM%' AND name ILIKE '%PUOR%' AND name ILIKE '%FEMME%';
    UPDATE "Product" SET images = ARRAY['/PERFUMES%20SAID/AFNAN/9PM%20REBEL.jpg'] WHERE brand = 'AFNAN' AND name ILIKE '%9PM%' AND name ILIKE '%REBEL%';
    UPDATE "Product" SET images = ARRAY['/PERFUMES%20SAID/AFNAN/9PM.jpg'] WHERE brand = 'AFNAN' AND name ILIKE '%9PM%';

    -- ======= AL HARAMAIN =======
    UPDATE "Product" SET images = ARRAY['/PERFUMES%20SAID/AL%20HARAMAIN/AMBER%20OUD%20AQUA%20DUBAI%20.JPG'] WHERE brand = 'AL HARAMAIN' AND name ILIKE '%AMBER%' AND name ILIKE '%OUD%' AND name ILIKE '%AQUA%' AND name ILIKE '%DUBAI%';
    UPDATE "Product" SET images = ARRAY['/PERFUMES%20SAID/AL%20HARAMAIN/AMBER%20OUD%20DUBAI%20NIGHT%20.JPG'] WHERE brand = 'AL HARAMAIN' AND name ILIKE '%AMBER%' AND name ILIKE '%OUD%' AND name ILIKE '%DUBAI%' AND name ILIKE '%NIGHT%';
    UPDATE "Product" SET images = ARRAY['/PERFUMES%20SAID/AL%20HARAMAIN/AMBER%20OUD%20GOLD%20DUBAI%20EDITION%20.JPG'] WHERE brand = 'AL HARAMAIN' AND name ILIKE '%AMBER%' AND name ILIKE '%OUD%' AND name ILIKE '%GOLD%' AND name ILIKE '%DUBAI%' AND name ILIKE '%EDITION%';
    UPDATE "Product" SET images = ARRAY['/PERFUMES%20SAID/AL%20HARAMAIN/AMBER%20OUD%20GOLD%20EDITION%20.JPG'] WHERE brand = 'AL HARAMAIN' AND name ILIKE '%AMBER%' AND name ILIKE '%OUD%' AND name ILIKE '%GOLD%' AND name ILIKE '%EDITION%';
    UPDATE "Product" SET images = ARRAY['/PERFUMES%20SAID/AL%20HARAMAIN/AMBER%20OUD%20GOLD%20EDITION%20EXTREME%20.JPG'] WHERE brand = 'AL HARAMAIN' AND name ILIKE '%AMBER%' AND name ILIKE '%OUD%' AND name ILIKE '%GOLD%' AND name ILIKE '%EDITION%' AND name ILIKE '%EXTREME%';
    UPDATE "Product" SET images = ARRAY['/PERFUMES%20SAID/AL%20HARAMAIN/AMBER%20OUD%20WHITE%20.JPG'] WHERE brand = 'AL HARAMAIN' AND name ILIKE '%AMBER%' AND name ILIKE '%OUD%' AND name ILIKE '%WHITE%';

    -- ======= ARMAF =======
    UPDATE "Product" SET images = ARRAY['/PERFUMES%20SAID/ARMAF/BEACH%20PARTY.jpg'] WHERE brand = 'ARMAF' AND name ILIKE '%BEACH%' AND name ILIKE '%PARTY%';
    UPDATE "Product" SET images = ARRAY['/PERFUMES%20SAID/ARMAF/CLUB%20DE%20NUIT%20ICONIC%20BLUE.jpg'] WHERE brand = 'ARMAF' AND name ILIKE '%CLUB%' AND name ILIKE '%NUIT%' AND name ILIKE '%ICONIC%' AND name ILIKE '%BLUE%';
    UPDATE "Product" SET images = ARRAY['/PERFUMES%20SAID/ARMAF/CLUB%20DE%20NUIT%20INTENSE.jpg'] WHERE brand = 'ARMAF' AND name ILIKE '%CLUB%' AND name ILIKE '%NUIT%' AND name ILIKE '%INTENSE%';
    UPDATE "Product" SET images = ARRAY['/PERFUMES%20SAID/ARMAF/CLUB%20DE%20NUIT%20MALEKA.jpg'] WHERE brand = 'ARMAF' AND name ILIKE '%CLUB%' AND name ILIKE '%NUIT%' AND name ILIKE '%MALEKA%';
    UPDATE "Product" SET images = ARRAY['/PERFUMES%20SAID/ARMAF/CLUB%20DE%20NUIT%20MILESTONE.jpg'] WHERE brand = 'ARMAF' AND name ILIKE '%CLUB%' AND name ILIKE '%NUIT%' AND name ILIKE '%MILESTONE%';
    UPDATE "Product" SET images = ARRAY['/PERFUMES%20SAID/ARMAF/CLUB%20DE%20NUIT%20SILLAGE.jpg'] WHERE brand = 'ARMAF' AND name ILIKE '%CLUB%' AND name ILIKE '%NUIT%' AND name ILIKE '%SILLAGE%';
    UPDATE "Product" SET images = ARRAY['/PERFUMES%20SAID/ARMAF/CLUB%20DE%20NUIT%20UNTOLD.jpg'] WHERE brand = 'ARMAF' AND name ILIKE '%CLUB%' AND name ILIKE '%NUIT%' AND name ILIKE '%UNTOLD%';
    UPDATE "Product" SET images = ARRAY['/PERFUMES%20SAID/ARMAF/CLUB%20DE%20NUIT%20URBAN%20ELIXIR.jpg'] WHERE brand = 'ARMAF' AND name ILIKE '%CLUB%' AND name ILIKE '%NUIT%' AND name ILIKE '%URBAN%' AND name ILIKE '%ELIXIR%';
    UPDATE "Product" SET images = ARRAY['/PERFUMES%20SAID/ARMAF/CLUB%20DE%20NUIT%20URBAN%20MAN.jpg'] WHERE brand = 'ARMAF' AND name ILIKE '%CLUB%' AND name ILIKE '%NUIT%' AND name ILIKE '%URBAN%' AND name ILIKE '%MAN%';
    UPDATE "Product" SET images = ARRAY['/PERFUMES%20SAID/ARMAF/ODYSSEY%20AQUA.jpg'] WHERE brand = 'ARMAF' AND name ILIKE '%ODYSSEY%' AND name ILIKE '%AQUA%';
    UPDATE "Product" SET images = ARRAY['/PERFUMES%20SAID/ARMAF/ODYSSEY%20BAHAMAS.jpg'] WHERE brand = 'ARMAF' AND name ILIKE '%ODYSSEY%' AND name ILIKE '%BAHAMAS%';
    UPDATE "Product" SET images = ARRAY['/PERFUMES%20SAID/ARMAF/ODYSSEY%20CANDEE.jpg'] WHERE brand = 'ARMAF' AND name ILIKE '%ODYSSEY%' AND name ILIKE '%CANDEE%';
    UPDATE "Product" SET images = ARRAY['/PERFUMES%20SAID/ARMAF/ODYSSEY%20HOMME%20WHITE.jpg'] WHERE brand = 'ARMAF' AND name ILIKE '%ODYSSEY%' AND name ILIKE '%HOMME%' AND name ILIKE '%WHITE%';
    UPDATE "Product" SET images = ARRAY['/PERFUMES%20SAID/ARMAF/ODYSSEY%20HOMME.jpg'] WHERE brand = 'ARMAF' AND name ILIKE '%ODYSSEY%' AND name ILIKE '%HOMME%';
    UPDATE "Product" SET images = ARRAY['/PERFUMES%20SAID/ARMAF/ODYSSEY%20LIMONI.jpg'] WHERE brand = 'ARMAF' AND name ILIKE '%ODYSSEY%' AND name ILIKE '%LIMONI%';
    UPDATE "Product" SET images = ARRAY['/PERFUMES%20SAID/ARMAF/ODYSSEY%20MANDARIN%20SKY%20ELIXIR.jpg'] WHERE brand = 'ARMAF' AND name ILIKE '%ODYSSEY%' AND name ILIKE '%MANDARIN%' AND name ILIKE '%SKY%' AND name ILIKE '%ELIXIR%';
    UPDATE "Product" SET images = ARRAY['/PERFUMES%20SAID/ARMAF/ODYSSEY%20MANDARIN%20SKY.jpg'] WHERE brand = 'ARMAF' AND name ILIKE '%ODYSSEY%' AND name ILIKE '%MANDARIN%' AND name ILIKE '%SKY%';
    UPDATE "Product" SET images = ARRAY['/PERFUMES%20SAID/ARMAF/ODYSSEY%20MEGA.jpg'] WHERE brand = 'ARMAF' AND name ILIKE '%ODYSSEY%' AND name ILIKE '%MEGA%';
    UPDATE "Product" SET images = ARRAY['/PERFUMES%20SAID/ARMAF/ODYSSEY%20SPECTRA.jpg'] WHERE brand = 'ARMAF' AND name ILIKE '%ODYSSEY%' AND name ILIKE '%SPECTRA%';

    -- ======= FRENCH AVENUE =======
    UPDATE "Product" SET images = ARRAY['/PERFUMES%20SAID/FRENCH%20AVENUE/AZZURE%20AOUD.jpg'] WHERE brand = 'FRENCH AVENUE' AND name ILIKE '%AZZURE%' AND name ILIKE '%AOUD%';
    UPDATE "Product" SET images = ARRAY['/PERFUMES%20SAID/FRENCH%20AVENUE/COCOA%20MORADO.jpg'] WHERE brand = 'FRENCH AVENUE' AND name ILIKE '%COCOA%' AND name ILIKE '%MORADO%';
    UPDATE "Product" SET images = ARRAY['/PERFUMES%20SAID/FRENCH%20AVENUE/LIQUID%20BRUN.jpg'] WHERE brand = 'FRENCH AVENUE' AND name ILIKE '%LIQUID%' AND name ILIKE '%BRUN%';
    UPDATE "Product" SET images = ARRAY['/PERFUMES%20SAID/FRENCH%20AVENUE/VENENO%20BIANCO.jpg'] WHERE brand = 'FRENCH AVENUE' AND name ILIKE '%VENENO%' AND name ILIKE '%BIANCO%';
    UPDATE "Product" SET images = ARRAY['/PERFUMES%20SAID/FRENCH%20AVENUE/VENENO%20SCARLET.jpg'] WHERE brand = 'FRENCH AVENUE' AND name ILIKE '%VENENO%' AND name ILIKE '%SCARLET%';
    UPDATE "Product" SET images = ARRAY['/PERFUMES%20SAID/FRENCH%20AVENUE/VULCAN%20BAIE.jpg'] WHERE brand = 'FRENCH AVENUE' AND name ILIKE '%VULCAN%' AND name ILIKE '%BAIE%';
    UPDATE "Product" SET images = ARRAY['/PERFUMES%20SAID/FRENCH%20AVENUE/VULCAN%20BLACK.jpg'] WHERE brand = 'FRENCH AVENUE' AND name ILIKE '%VULCAN%' AND name ILIKE '%BLACK%';
    UPDATE "Product" SET images = ARRAY['/PERFUMES%20SAID/FRENCH%20AVENUE/VULCAN%20FEU.jpg'] WHERE brand = 'FRENCH AVENUE' AND name ILIKE '%VULCAN%' AND name ILIKE '%FEU%';

    -- ======= LATTAFA =======
    UPDATE "Product" SET images = ARRAY['/PERFUMES%20SAID/LATTAFA/AL%20OUD%20AMETHYST.jpg'] WHERE brand = 'LATTAFA' AND name ILIKE '%OUD%' AND name ILIKE '%AMETHYST%';
    UPDATE "Product" SET images = ARRAY['/PERFUMES%20SAID/LATTAFA/AL%20OUD%20FOR%20GLORY.jpg'] WHERE brand = 'LATTAFA' AND name ILIKE '%OUD%' AND name ILIKE '%FOR%' AND name ILIKE '%GLORY%';
    UPDATE "Product" SET images = ARRAY['/PERFUMES%20SAID/LATTAFA/AL%20OUD%20HONOR%20%26%20GLORY.jpg'] WHERE brand = 'LATTAFA' AND name ILIKE '%OUD%' AND name ILIKE '%HONOR%' AND name ILIKE '%GLORY%';
    UPDATE "Product" SET images = ARRAY['/PERFUMES%20SAID/LATTAFA/AL%20OUD%20NOBLE%20BLUSH.jpg'] WHERE brand = 'LATTAFA' AND name ILIKE '%OUD%' AND name ILIKE '%NOBLE%' AND name ILIKE '%BLUSH%';
    UPDATE "Product" SET images = ARRAY['/PERFUMES%20SAID/LATTAFA/AL%20OUD%20SUBLIME.jpg'] WHERE brand = 'LATTAFA' AND name ILIKE '%OUD%' AND name ILIKE '%SUBLIME%';
    UPDATE "Product" SET images = ARRAY['/PERFUMES%20SAID/LATTAFA/ART%20OF%20UNIVERSE.jpg'] WHERE brand = 'LATTAFA' AND name ILIKE '%ART%' AND name ILIKE '%UNIVERSE%';
    UPDATE "Product" SET images = ARRAY['/PERFUMES%20SAID/LATTAFA/ASAD%20BOURBON.jpg'] WHERE brand = 'LATTAFA' AND name ILIKE '%ASAD%' AND name ILIKE '%BOURBON%';
    UPDATE "Product" SET images = ARRAY['/PERFUMES%20SAID/LATTAFA/ASAD%20ELIXIR.jpg'] WHERE brand = 'LATTAFA' AND name ILIKE '%ASAD%' AND name ILIKE '%ELIXIR%';
    UPDATE "Product" SET images = ARRAY['/PERFUMES%20SAID/LATTAFA/ASAD%20ZANZIBAR%20LIMITED%20EDITION.jpg'] WHERE brand = 'LATTAFA' AND name ILIKE '%ASAD%' AND name ILIKE '%ZANZIBAR%' AND name ILIKE '%LIMITED%' AND name ILIKE '%EDITION%';
    UPDATE "Product" SET images = ARRAY['/PERFUMES%20SAID/LATTAFA/ASAD%20ZANZIBAR.jpg'] WHERE brand = 'LATTAFA' AND name ILIKE '%ASAD%' AND name ILIKE '%ZANZIBAR%';
    UPDATE "Product" SET images = ARRAY['/PERFUMES%20SAID/LATTAFA/ASAD.jpg'] WHERE brand = 'LATTAFA' AND name ILIKE '%ASAD%';
    UPDATE "Product" SET images = ARRAY['/PERFUMES%20SAID/LATTAFA/ECLAIRE%20BANOFFI.jpg'] WHERE brand = 'LATTAFA' AND name ILIKE '%ECLAIRE%' AND name ILIKE '%BANOFFI%';
    UPDATE "Product" SET images = ARRAY['/PERFUMES%20SAID/LATTAFA/ECLAIRE%20PISTACHE.jpg'] WHERE brand = 'LATTAFA' AND name ILIKE '%ECLAIRE%' AND name ILIKE '%PISTACHE%';
    UPDATE "Product" SET images = ARRAY['/PERFUMES%20SAID/LATTAFA/ECLAIRE.jpg'] WHERE brand = 'LATTAFA' AND name ILIKE '%ECLAIRE%';
    UPDATE "Product" SET images = ARRAY['/PERFUMES%20SAID/LATTAFA/FAKHAR%20EXTRAIT.jpg'] WHERE brand = 'LATTAFA' AND name ILIKE '%FAKHAR%' AND name ILIKE '%EXTRAIT%';
    UPDATE "Product" SET images = ARRAY['/PERFUMES%20SAID/LATTAFA/FAKHAR%20PLATIN.jpg'] WHERE brand = 'LATTAFA' AND name ILIKE '%FAKHAR%' AND name ILIKE '%PLATIN%';
    UPDATE "Product" SET images = ARRAY['/PERFUMES%20SAID/LATTAFA/FAKHAR%20PRIDE.jpg'] WHERE brand = 'LATTAFA' AND name ILIKE '%FAKHAR%' AND name ILIKE '%PRIDE%';
    UPDATE "Product" SET images = ARRAY['/PERFUMES%20SAID/LATTAFA/FAKHAR%20ROSE.jpg'] WHERE brand = 'LATTAFA' AND name ILIKE '%FAKHAR%' AND name ILIKE '%ROSE%';
    UPDATE "Product" SET images = ARRAY['/PERFUMES%20SAID/LATTAFA/HER%20CONFESSION.jpg'] WHERE brand = 'LATTAFA' AND name ILIKE '%HER%' AND name ILIKE '%CONFESSION%';
    UPDATE "Product" SET images = ARRAY['/PERFUMES%20SAID/LATTAFA/HIS%20CONFESSION.jpg'] WHERE brand = 'LATTAFA' AND name ILIKE '%HIS%' AND name ILIKE '%CONFESSION%';
    UPDATE "Product" SET images = ARRAY['/PERFUMES%20SAID/LATTAFA/KHAMRAH%20DUKHAN.jpg'] WHERE brand = 'LATTAFA' AND name ILIKE '%KHAMRAH%' AND name ILIKE '%DUKHAN%';
    UPDATE "Product" SET images = ARRAY['/PERFUMES%20SAID/LATTAFA/KHAMRAH%20QAWHA.jpg'] WHERE brand = 'LATTAFA' AND name ILIKE '%KHAMRAH%' AND name ILIKE '%QAWHA%';
    UPDATE "Product" SET images = ARRAY['/PERFUMES%20SAID/LATTAFA/KHAMRAH.jpg'] WHERE brand = 'LATTAFA' AND name ILIKE '%KHAMRAH%';
    UPDATE "Product" SET images = ARRAY['/PERFUMES%20SAID/LATTAFA/MAYAR%20CHERRY.jpg'] WHERE brand = 'LATTAFA' AND name ILIKE '%MAYAR%' AND name ILIKE '%CHERRY%';
    UPDATE "Product" SET images = ARRAY['/PERFUMES%20SAID/LATTAFA/MAYAR%20NATURAL%20INTENSE.jpg'] WHERE brand = 'LATTAFA' AND name ILIKE '%MAYAR%' AND name ILIKE '%NATURAL%' AND name ILIKE '%INTENSE%';
    UPDATE "Product" SET images = ARRAY['/PERFUMES%20SAID/LATTAFA/MAYAR.jpg'] WHERE brand = 'LATTAFA' AND name ILIKE '%MAYAR%';
    UPDATE "Product" SET images = ARRAY['/PERFUMES%20SAID/LATTAFA/THE%20KINGDOM.jpg'] WHERE brand = 'LATTAFA' AND name ILIKE '%THE%' AND name ILIKE '%KINGDOM%';
    UPDATE "Product" SET images = ARRAY['/PERFUMES%20SAID/LATTAFA/YARA%20CANDY.jpg'] WHERE brand = 'LATTAFA' AND name ILIKE '%YARA%' AND name ILIKE '%CANDY%';
    UPDATE "Product" SET images = ARRAY['/PERFUMES%20SAID/LATTAFA/YARA%20ELIXIR.jpg'] WHERE brand = 'LATTAFA' AND name ILIKE '%YARA%' AND name ILIKE '%ELIXIR%';
    UPDATE "Product" SET images = ARRAY['/PERFUMES%20SAID/LATTAFA/YARA%20MOI.jpg'] WHERE brand = 'LATTAFA' AND name ILIKE '%YARA%' AND name ILIKE '%MOI%';
    UPDATE "Product" SET images = ARRAY['/PERFUMES%20SAID/LATTAFA/YARA%20TOUS.jpg'] WHERE brand = 'LATTAFA' AND name ILIKE '%YARA%' AND name ILIKE '%TOUS%';
    UPDATE "Product" SET images = ARRAY['/PERFUMES%20SAID/LATTAFA/YARA.jpg'] WHERE brand = 'LATTAFA' AND name ILIKE '%YARA%';

    -- ======= PERFUMES SAID =======
    UPDATE "Product" SET images = ARRAY['/PERFUMES%20SAID/PERFUMES%20SAID/BHARARA%20KING.jpg'] WHERE brand = 'BHARARA' AND name ILIKE '%BHARARA%' AND name ILIKE '%KING%';

    -- ======= RASASI =======
    UPDATE "Product" SET images = ARRAY['/PERFUMES%20SAID/RASASI/HAWAS%20BLACK.jpg'] WHERE brand = 'RASASI' AND name ILIKE '%HAWAS%' AND name ILIKE '%BLACK%';
    UPDATE "Product" SET images = ARRAY['/PERFUMES%20SAID/RASASI/HAWAS%20DIVA.jpg'] WHERE brand = 'RASASI' AND name ILIKE '%HAWAS%' AND name ILIKE '%DIVA%';
    UPDATE "Product" SET images = ARRAY['/PERFUMES%20SAID/RASASI/HAWAS%20ELIXIR.jpg'] WHERE brand = 'RASASI' AND name ILIKE '%HAWAS%' AND name ILIKE '%ELIXIR%';
    UPDATE "Product" SET images = ARRAY['/PERFUMES%20SAID/RASASI/HAWAS%20FIRE.jpg'] WHERE brand = 'RASASI' AND name ILIKE '%HAWAS%' AND name ILIKE '%FIRE%';
    UPDATE "Product" SET images = ARRAY['/PERFUMES%20SAID/RASASI/HAWAS%20FOR%20HER.jpg'] WHERE brand = 'RASASI' AND name ILIKE '%HAWAS%' AND name ILIKE '%FOR%' AND name ILIKE '%HER%';
    UPDATE "Product" SET images = ARRAY['/PERFUMES%20SAID/RASASI/HAWAS%20FOR%20HIM.jpg'] WHERE brand = 'RASASI' AND name ILIKE '%HAWAS%' AND name ILIKE '%FOR%' AND name ILIKE '%HIM%';
    UPDATE "Product" SET images = ARRAY['/PERFUMES%20SAID/RASASI/HAWAS%20ICE.jpg'] WHERE brand = 'RASASI' AND name ILIKE '%HAWAS%' AND name ILIKE '%ICE%';
    UPDATE "Product" SET images = ARRAY['/PERFUMES%20SAID/RASASI/HAWAS%20KOBRA%20.JPG'] WHERE brand = 'RASASI' AND name ILIKE '%HAWAS%' AND name ILIKE '%KOBRA%';
    UPDATE "Product" SET images = ARRAY['/PERFUMES%20SAID/RASASI/HAWAS%20LONDON.jpg'] WHERE brand = 'RASASI' AND name ILIKE '%HAWAS%' AND name ILIKE '%LONDON%';
    UPDATE "Product" SET images = ARRAY['/PERFUMES%20SAID/RASASI/HAWAS%20MALIBU.jpg'] WHERE brand = 'RASASI' AND name ILIKE '%HAWAS%' AND name ILIKE '%MALIBU%';
    UPDATE "Product" SET images = ARRAY['/PERFUMES%20SAID/RASASI/HAWAS%20PINK.jpg'] WHERE brand = 'RASASI' AND name ILIKE '%HAWAS%' AND name ILIKE '%PINK%';
    UPDATE "Product" SET images = ARRAY['/PERFUMES%20SAID/RASASI/HAWAS%20TROPICAL%20.JPG'] WHERE brand = 'RASASI' AND name ILIKE '%HAWAS%' AND name ILIKE '%TROPICAL%';
    UPDATE "Product" SET images = ARRAY['/PERFUMES%20SAID/RASASI/HAWAS%20VERDE.jpg'] WHERE brand = 'RASASI' AND name ILIKE '%HAWAS%' AND name ILIKE '%VERDE%';

    -- ======= VALENTINO =======
    UPDATE "Product" SET images = ARRAY['/PERFUMES%20SAID/VALENTINO/Valentino%20Born%20In%20Roma%20.jpg'] WHERE brand = 'VALENTINO' AND name ILIKE '%Born%' AND name ILIKE '%Roma%';
    UPDATE "Product" SET images = ARRAY['/PERFUMES%20SAID/VALENTINO/Valentino%20Born%20In%20Roma%20Donna%20Green%20Stravaganza%20.jpg'] WHERE brand = 'VALENTINO' AND name ILIKE '%Born%' AND name ILIKE '%Roma%' AND name ILIKE '%Donna%' AND name ILIKE '%Green%' AND name ILIKE '%Stravaganza%';
    UPDATE "Product" SET images = ARRAY['/PERFUMES%20SAID/VALENTINO/Valentino%20Uomo%20.jpg'] WHERE brand = 'VALENTINO' AND name ILIKE '%Uomo%';
    UPDATE "Product" SET images = ARRAY['/PERFUMES%20SAID/VALENTINO/Valentino%20Uomo%20Born%20In%20Roma%20Extradose%20.jpg'] WHERE brand = 'VALENTINO' AND name ILIKE '%Uomo%' AND name ILIKE '%Born%' AND name ILIKE '%Roma%' AND name ILIKE '%Extradose%';
    UPDATE "Product" SET images = ARRAY['/PERFUMES%20SAID/VALENTINO/Valentino%20Uomo%20Born%20In%20Roma%20Green%20Stravaganza%20.jpg'] WHERE brand = 'VALENTINO' AND name ILIKE '%Uomo%' AND name ILIKE '%Born%' AND name ILIKE '%Roma%' AND name ILIKE '%Green%' AND name ILIKE '%Stravaganza%';

    -- ======= XERJOFF =======
    UPDATE "Product" SET images = ARRAY['/PERFUMES%20SAID/XERJOFF/CORO.jpg'] WHERE brand = 'XERJOFF' AND name ILIKE '%CORO%';
    UPDATE "Product" SET images = ARRAY['/PERFUMES%20SAID/XERJOFF/ERBA%20GOLD.jpg'] WHERE brand = 'XERJOFF' AND name ILIKE '%ERBA%' AND name ILIKE '%GOLD%';
    UPDATE "Product" SET images = ARRAY['/PERFUMES%20SAID/XERJOFF/ERBA%20PURA%20100ml.jpg'] WHERE brand = 'XERJOFF' AND name ILIKE '%ERBA%' AND name ILIKE '%PURA%' AND name ILIKE '%100ml%';
    UPDATE "Product" SET images = ARRAY['/PERFUMES%20SAID/XERJOFF/ERBA%20PURA%2050ml.jpg'] WHERE brand = 'XERJOFF' AND name ILIKE '%ERBA%' AND name ILIKE '%PURA%' AND name ILIKE '%50ml%';
    UPDATE "Product" SET images = ARRAY['/PERFUMES%20SAID/XERJOFF/OVERDOSE%20ACCENTO.jpg'] WHERE brand = 'XERJOFF' AND name ILIKE '%OVERDOSE%' AND name ILIKE '%ACCENTO%';
    UPDATE "Product" SET images = ARRAY['/PERFUMES%20SAID/XERJOFF/SOPRANO.jpg'] WHERE brand = 'XERJOFF' AND name ILIKE '%SOPRANO%';
    UPDATE "Product" SET images = ARRAY['/PERFUMES%20SAID/XERJOFF/TORINO%2021.jpg'] WHERE brand = 'XERJOFF' AND name ILIKE '%TORINO%';
    UPDATE "Product" SET images = ARRAY['/PERFUMES%20SAID/XERJOFF/WARDASINA.jpg'] WHERE brand = 'XERJOFF' AND name ILIKE '%WARDASINA%';

    -- Verificar resultados:
    -- SELECT brand, name, images FROM "Product" WHERE images IS NOT NULL AND array_length(images, 1) > 0 ORDER BY brand, name;